#!/usr/bin/expect -f
set timeout 60
spawn scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null test/simple_hkcapture_test.py lqj@192.168.0.121:/home/lqj/liquid/test/simple_hkcapture_test.py
expect {
    "*password*" { send "admin\r"; exp_continue }
    "*Password*" { send "admin\r"; exp_continue }
    "*(yes/no)*" { send "yes\r"; exp_continue }
    "*Are you sure*" { send "yes\r"; exp_continue }
    eof
}
