channel1:
  annotation_count: 1
  areas:
    area_1:
      height: 20mm
      init_status: 0
      name: 通道1_区域1
      state: 默认
  boxes:
  - - 650
    - 455
    - 896
  fixed_bottoms:
  - 635
  fixed_init_levels:
  - 0.0
  fixed_tops:
  - 189
  init_levels:
  - - 632
    - 633
  last_updated: '2026-04-13 00:00:00'
channel10:
  annotation_count: 1
  areas:
    area_1:
      height: 20mm
      init_status: 0
      name: 通道10_区域1
      state: 默认
  boxes:
  - - 650
    - 455
    - 896
  fixed_bottoms:
  - 635
  fixed_init_levels:
  - 0.0
  fixed_tops:
  - 189
  init_levels:
  - - 632
    - 633
  last_updated: '2026-04-13 00:00:00'
channel11:
  annotation_count: 1
  areas:
    area_1:
      height: 20mm
      init_status: 0
      name: 通道11_区域1
      state: 默认
  boxes:
  - - 650
    - 455
    - 896
  fixed_bottoms:
  - 635
  fixed_init_levels:
  - 0.0
  fixed_tops:
  - 189
  init_levels:
  - - 632
    - 633
  last_updated: '2026-04-13 00:00:00'
channel12:
  annotation_count: 1
  areas:
    area_1:
      height: 20mm
      init_status: 0
      name: 通道12_区域1
      state: 默认
  boxes:
  - - 650
    - 455
    - 896
  fixed_bottoms:
  - 635
  fixed_init_levels:
  - 0.0
  fixed_tops:
  - 189
  init_levels:
  - - 632
    - 633
  last_updated: '2026-04-13 00:00:00'
channel13:
  annotation_count: 1
  areas:
    area_1:
      height: 20mm
      init_status: 0
      name: 通道13_区域1
      state: 默认
  boxes:
  - - 650
    - 455
    - 896
  fixed_bottoms:
  - 635
  fixed_init_levels:
  - 0.0
  fixed_tops:
  - 189
  init_levels:
  - - 632
    - 633
  last_updated: '2026-04-13 00:00:00'
channel14:
  annotation_count: 1
  areas:
    area_1:
      height: 20mm
      init_status: 0
      name: 通道14_区域1
      state: 默认
  boxes:
  - - 650
    - 455
    - 896
  fixed_bottoms:
  - 635
  fixed_init_levels:
  - 0.0
  fixed_tops:
  - 189
  init_levels:
  - - 632
    - 633
  last_updated: '2026-04-13 00:00:00'
channel15:
  annotation_count: 1
  areas:
    area_1:
      height: 20mm
      init_status: 0
      name: 通道15_区域1
      state: 默认
  boxes:
  - - 650
    - 455
    - 896
  fixed_bottoms:
  - 635
  fixed_init_levels:
  - 0.0
  fixed_tops:
  - 189
  init_levels:
  - - 632
    - 633
  last_updated: '2026-04-13 00:00:00'
channel16:
  annotation_count: 1
  areas:
    area_1:
      height: 20mm
      init_status: 0
      name: 通道16_区域1
      state: 默认
  boxes:
  - - 650
    - 455
    - 896
  fixed_bottoms:
  - 635
  fixed_init_levels:
  - 0.0
  fixed_tops:
  - 189
  init_levels:
  - - 632
    - 633
  last_updated: '2026-04-13 00:00:00'
channel2:
  annotation_count: 1
  areas:
    area_1:
      height: 20mm
      init_status: 0
      name: 通道2_区域1
      state: 默认
  boxes:
  - - 650
    - 455
    - 896
  fixed_bottoms:
  - 635
  fixed_init_levels:
  - 0.0
  fixed_tops:
  - 189
  init_levels:
  - - 632
    - 633
  last_updated: '2026-04-13 00:00:00'
channel3:
  annotation_count: 1
  areas:
    area_1:
      height: 20mm
      init_status: 0
      name: 通道3_区域1
      state: 默认
  boxes:
  - - 650
    - 455
    - 896
  fixed_bottoms:
  - 635
  fixed_init_levels:
  - 0.0
  fixed_tops:
  - 189
  init_levels:
  - - 632
    - 633
  last_updated: '2026-04-13 00:00:00'
channel4:
  annotation_count: 1
  areas:
    area_1:
      height: 20mm
      init_status: 0
      name: 通道4_区域1
      state: 默认
  boxes:
  - - 650
    - 455
    - 896
  fixed_bottoms:
  - 635
  fixed_init_levels:
  - 0.0
  fixed_tops:
  - 189
  init_levels:
  - - 632
    - 633
  last_updated: '2026-04-13 00:00:00'
channel5:
  annotation_count: 1
  areas:
    area_1:
      height: 20mm
      init_status: 0
      name: 通道5_区域1
      state: 默认
  boxes:
  - - 650
    - 455
    - 896
  fixed_bottoms:
  - 635
  fixed_init_levels:
  - 0.0
  fixed_tops:
  - 189
  init_levels:
  - - 632
    - 633
  last_updated: '2026-04-13 00:00:00'
channel6:
  annotation_count: 1
  areas:
    area_1:
      height: 20mm
      init_status: 0
      name: 通道6_区域1
      state: 默认
  boxes:
  - - 650
    - 455
    - 896
  fixed_bottoms:
  - 635
  fixed_init_levels:
  - 0.0
  fixed_tops:
  - 189
  init_levels:
  - - 632
    - 633
  last_updated: '2026-04-13 00:00:00'
channel7:
  annotation_count: 1
  areas:
    area_1:
      height: 20mm
      init_status: 0
      name: 通道7_区域1
      state: 默认
  boxes:
  - - 650
    - 455
    - 896
  fixed_bottoms:
  - 635
  fixed_init_levels:
  - 0.0
  fixed_tops:
  - 189
  init_levels:
  - - 632
    - 633
  last_updated: '2026-04-13 00:00:00'
channel8:
  annotation_count: 1
  areas:
    area_1:
      height: 20mm
      init_status: 0
      name: 通道8_区域1
      state: 默认
  boxes:
  - - 650
    - 455
    - 896
  fixed_bottoms:
  - 635
  fixed_init_levels:
  - 0.0
  fixed_tops:
  - 189
  init_levels:
  - - 632
    - 633
  last_updated: '2026-04-13 00:00:00'
channel9:
  annotation_count: 1
  areas:
    area_1:
      height: 20mm
      init_status: 0
      name: 通道9_区域1
      state: 默认
  boxes:
  - - 650
    - 455
    - 896
  fixed_bottoms:
  - 635
  fixed_init_levels:
  - 0.0
  fixed_tops:
  - 189
  init_levels:
  - - 632
    - 633
  last_updated: '2026-04-13 00:00:00'
