channel1:
  enabled: true
  ip: 192.168.0.27
  name: 通道1
  password: cei345678
  port: 8000
  retry_count: 3
  rtsp_url: rtsp://admin:cei345678@192.168.0.27:8000/stream1
  stream_path: stream1
  timeout: 10
  username: admin
channel2:
  enabled: false
  ip: 192.168.0.28
  name: 通道2
  password: cei345678
  port: 8000
  retry_count: 3
  rtsp_url: rtsp://admin:cei345678@192.168.0.28:8000/stream1
  stream_path: stream1
  timeout: 10
  username: admin
