test_model:
  areas:
    area_1:
      height: 20mm
      name: test_model_区域1
    area_2:
      height: 20mm
      name: test_model_区域2
  bottoms:
  - !!python/tuple
    - 1082
    - 1028
  - !!python/tuple
    - 1140
    - 283
  boxes:
  - !!python/tuple
    - 1078
    - 934
    - 192
  - !!python/tuple
    - 1141
    - 222
    - 128
  tops:
  - !!python/tuple
    - 1076
    - 839
  - !!python/tuple
    - 1140
    - 159
