channel1:
  boxes:
  - - 623
    - 427
    - 800
  fixed_bottoms:
  - 747
  fixed_tops:
  - 107
  init_levels:
  - - 623
    - 427
  fixed_init_levels:
  - 10.0
  annotation_count: 1
  areas:
    area_1:
      name: 通道1_区域1
      height: 20mm
      state: 默认
      init_status: 0
  last_updated: '2026-04-13 16:57:27'
channel4:
  boxes:
  - - 631
    - 446
    - 864
  fixed_bottoms:
  - 791
  fixed_tops:
  - 100
  init_levels:
  - - 631
    - 446
  fixed_init_levels:
  - 9.99
  annotation_count: 1
  areas:
    area_1:
      name: 通道4_区域1
      height: 20mm
      state: 默认
      init_status: 0
  last_updated: '2026-04-13 14:35:31'
