channel1:
  boxes:
  - - 927
    - 520
    - 288
  fixed_bottoms:
  - 635
  fixed_tops:
  - 404
  init_levels:
  - - 927
    - 520
  fixed_init_levels:
  - 9.96
  annotation_count: 1
  areas:
    area_1:
      name: 通道1_区域1
      height: 20mm
      state: 默认
      init_status: 0
  last_updated: '2026-03-17 15:00:46'
